"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense } from "react";
import jsPDF from "jspdf";
import { getSamplePlan } from "../plan/samplePlan";

function SaveFlow() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [email, setEmail] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");

  const zip = searchParams.get("zip") || "";
  const grassType = searchParams.get("grassType") || "";
  const lawnSize = searchParams.get("lawnSize") || "";
  const lawnGoal = searchParams.get("lawnGoal") || "";
  const path = searchParams.get("path") || "novice";

  const grassLabels: Record<string, string> = {
    bermuda: "Bermuda", zoysia: "Zoysia", fescue_kbg: "Fescue/KBG",
    st_augustine: "St. Augustine", not_sure: "Your lawn",
  };
  const goalLabels: Record<string, string> = {
    fix: "Fix It", maintain: "Maintain", perfect: "Perfect It", not_sure: "General Care",
  };

  const downloadPDF = () => {
    const plan = getSamplePlan(grassType, lawnSize, lawnGoal, path);
    const totalTasks = plan.reduce(
      (sum, m) => sum + m.weeks.reduce((ws, w) => ws + w.tasks.length, 0), 0
    );

    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 48;
    const contentW = pageW - margin * 2;
    let y = margin;

    const checkPage = (needed: number) => {
      if (y + needed > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
    };

    doc.setFillColor(74, 103, 65);
    doc.rect(0, 0, pageW, 72, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text("LawnHQ", margin, 44);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Your 90-Day Lawn Care Plan", pageW - margin, 44, { align: "right" });
    y = 100;

    doc.setFillColor(245, 242, 235);
    doc.roundedRect(margin, y, contentW, 64, 6, 6, "F");
    doc.setFontSize(10);
    doc.setTextColor(45, 42, 38);
    doc.setFont("helvetica", "normal");
    doc.text(`Grass: ${grassLabels[grassType] || grassType}  |  Size: ${lawnSize}  |  Goal: ${goalLabels[lawnGoal] || lawnGoal}`, margin + 16, y + 26);
    doc.setTextColor(100, 95, 90);
    doc.text(`Location: ${zip}  |  ${totalTasks} tasks over 12 weeks  |  Generated ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`, margin + 16, y + 44);
    y += 84;

    for (const month of plan) {
      checkPage(50);
      doc.setFillColor(74, 103, 65);
      doc.roundedRect(margin, y, contentW, 32, 4, 4, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(255, 255, 255);
      doc.text(month.name, margin + 14, y + 21);
      y += 44;

      for (const week of month.weeks) {
        checkPage(30);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(196, 120, 90);
        doc.text(week.label.toUpperCase(), margin + 4, y);
        y += 6;
        doc.setDrawColor(220, 215, 208);
        doc.setLineWidth(0.5);
        doc.line(margin + 4, y, margin + contentW - 4, y);
        y += 10;

        for (const task of week.tasks) {
          checkPage(28);
          doc.setFont("helvetica", "normal");
          doc.setFontSize(9.5);
          doc.setTextColor(60, 56, 50);
          doc.setDrawColor(180, 175, 168);
          doc.setLineWidth(0.8);
          doc.rect(margin + 8, y - 7, 8, 8);
          const lines = doc.splitTextToSize(task, contentW - 32);
          doc.text(lines, margin + 22, y);
          y += lines.length * 13 + 4;
        }
        y += 8;
      }
      y += 6;
    }

    checkPage(40);
    doc.setDrawColor(220, 215, 208);
    doc.line(margin, y, margin + contentW, y);
    y += 16;
    doc.setFontSize(8);
    doc.setTextColor(150, 145, 138);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by LawnHQ — mylawnhq.com", margin, y);
    doc.text("Your plan adapts as you go. Upload a lawn photo for personalized diagnosis.", margin, y + 12);

    doc.save("LawnHQ-90-Day-Plan.pdf");
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      setError("Please enter a valid email address");
      return;
    }
    // In a real implementation, this would call Supabase to create the account
    setSubmitted(true);
  };

  if (submitted) {
    return (
      <div className="min-h-screen bg-cream flex items-center justify-center px-4">
        <div className="max-w-md w-full text-center">
          <div className="text-4xl mb-4">&#127793;</div>
          <h2 className="font-display text-2xl font-bold text-deep-brown mb-3">
            Plan Saved!
          </h2>
          <p className="text-deep-brown/60 mb-8">
            We&rsquo;ve sent a confirmation to {email}. Your personalized 90-day
            plan is ready whenever you are.
          </p>

          {/* Upsell */}
          <div className="bg-white rounded-xl border border-deep-brown/10 p-6 text-left mb-6">
            <h3 className="font-display font-semibold text-deep-brown mb-3">
              Unlock Pro
            </h3>
            <p className="text-sm text-deep-brown/60 mb-4">
              You&rsquo;re on the free plan. Upgrade to unlock:
            </p>
            <ul className="space-y-2 text-sm text-deep-brown/70 mb-5">
              {[
                "Unlimited AI lawn expert chat",
                "Photo diagnosis (snap a pic, get answers)",
                "Product recommendations with buy links",
                "Spreader calculator",
                "Push notifications for weather alerts",
              ].map((item) => (
                <li key={item} className="flex items-center gap-2">
                  <svg className="w-4 h-4 text-lawn flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                  {item}
                </li>
              ))}
            </ul>
            <p className="text-sm font-semibold text-deep-brown mb-4">
              $9/month or $79/year{" "}
              <span className="text-ochre font-normal">(save 27%)</span>
            </p>
            <button className="w-full bg-terracotta text-white font-semibold py-3 rounded-lg text-sm hover:bg-terracotta/90 transition-colors">
              START 7-DAY FREE TRIAL &rarr;
            </button>
            <p className="text-xs text-deep-brown/40 text-center mt-2">
              Cancel anytime. No questions asked.
            </p>
          </div>

          <div className="flex items-center gap-3 mb-6">
            <div className="flex-1 h-px bg-deep-brown/10" />
            <span className="text-xs text-deep-brown/40">
              or continue with free plan
            </span>
            <div className="flex-1 h-px bg-deep-brown/10" />
          </div>

          <button
            onClick={downloadPDF}
            className="w-full flex items-center justify-center gap-2 bg-deep-brown text-white font-semibold py-3 rounded-lg text-sm hover:bg-deep-brown/90 transition-colors mb-3"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download My Plan (PDF)
          </button>
          <button
            onClick={() => router.push("/dashboard")}
            className="w-full bg-lawn text-white font-semibold py-3 rounded-lg text-sm hover:bg-lawn/90 transition-colors"
          >
            GO TO MY DASHBOARD &rarr;
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-cream flex items-center justify-center px-4">
      <div className="max-w-md w-full">
        <div className="text-center mb-8">
          <h2 className="font-display text-2xl sm:text-3xl font-bold text-deep-brown">
            Save your personalized plan
          </h2>
          <p className="mt-3 text-deep-brown/60">Enter your email to:</p>
          <ul className="mt-3 space-y-1.5 text-sm text-deep-brown/70">
            <li>Save your plan and lawn photo</li>
            <li>Get reminders when tasks are due</li>
            <li>Track your progress over time</li>
          </ul>
        </div>

        <form onSubmit={handleSubmit} className="bg-white rounded-xl border border-deep-brown/10 p-6">
          <label
            htmlFor="email"
            className="block text-sm font-medium text-deep-brown/70 mb-2"
          >
            Email address
          </label>
          <input
            id="email"
            type="email"
            value={email}
            onChange={(e) => {
              setEmail(e.target.value);
              setError("");
            }}
            placeholder="you@example.com"
            className="w-full px-4 py-3 rounded-lg border border-deep-brown/15 bg-cream/50 text-deep-brown placeholder:text-deep-brown/30 focus:outline-none focus:ring-2 focus:ring-lawn/30"
          />
          {error && <p className="mt-2 text-sm text-red-600">{error}</p>}

          <button
            type="submit"
            className="mt-4 w-full bg-terracotta text-white font-semibold py-3.5 rounded-lg text-sm hover:bg-terracotta/90 transition-colors tracking-wide"
          >
            SAVE MY PLAN & CREATE ACCOUNT &rarr;
          </button>

          <div className="flex items-center gap-3 mt-4">
            <div className="flex-1 h-px bg-deep-brown/10" />
            <span className="text-xs text-deep-brown/40">or</span>
            <div className="flex-1 h-px bg-deep-brown/10" />
          </div>

          <button
            type="button"
            onClick={downloadPDF}
            className="mt-4 w-full flex items-center justify-center gap-2 border border-deep-brown/15 text-deep-brown/70 font-medium py-3 rounded-lg text-sm hover:border-deep-brown/30 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download PDF instead
          </button>

          <p className="mt-3 text-xs text-deep-brown/40 text-center">
            By continuing, you agree to our Terms and Privacy Policy. We&rsquo;ll
            never spam you.
          </p>
        </form>
      </div>
    </div>
  );
}

export default function SavePage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-cream flex items-center justify-center">
          <div className="text-deep-brown/40">Loading...</div>
        </div>
      }
    >
      <SaveFlow />
    </Suspense>
  );
}
