/**
 * Zip code to climate zone / grass type mapping.
 * Uses the first 3 digits of the zip to map to a region.
 * This is a simplified mapping — a full dataset would cover all 999 prefixes.
 */

type ClimateZone = "warm" | "cool" | "transition";

interface RegionInfo {
  zone: ClimateZone;
  region: string;
  suggestedGrass: string;
  suggestedGrassKey: string;
}

// First 3 digits of zip → region info
const zipPrefixMap: Record<string, RegionInfo> = {
  // Southeast - Warm season
  "300": { zone: "warm", region: "Atlanta, GA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "301": { zone: "warm", region: "Atlanta, GA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "303": { zone: "warm", region: "Atlanta, GA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "305": { zone: "warm", region: "Miami, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "321": { zone: "warm", region: "Orlando, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "322": { zone: "warm", region: "Jacksonville, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "326": { zone: "warm", region: "Central FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "327": { zone: "warm", region: "Orlando, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "328": { zone: "warm", region: "Orlando, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "330": { zone: "warm", region: "South FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "331": { zone: "warm", region: "South FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "332": { zone: "warm", region: "South FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "333": { zone: "warm", region: "Fort Lauderdale, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "334": { zone: "warm", region: "West Palm Beach, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "335": { zone: "warm", region: "Tampa, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "336": { zone: "warm", region: "Tampa, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "337": { zone: "warm", region: "St. Petersburg, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "338": { zone: "warm", region: "Lakeland, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "339": { zone: "warm", region: "Fort Myers, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "346": { zone: "warm", region: "Tampa, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "347": { zone: "warm", region: "Clearwater, FL", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "349": { zone: "warm", region: "Florida Panhandle", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "350": { zone: "warm", region: "Birmingham, AL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "360": { zone: "warm", region: "Montgomery, AL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "365": { zone: "warm", region: "Mobile, AL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "370": { zone: "transition", region: "Nashville, TN", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "372": { zone: "transition", region: "Nashville, TN", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "376": { zone: "transition", region: "Chattanooga, TN", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "377": { zone: "transition", region: "Knoxville, TN", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "380": { zone: "warm", region: "Memphis, TN", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "386": { zone: "warm", region: "Mississippi", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "390": { zone: "warm", region: "Mississippi", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "394": { zone: "warm", region: "Mississippi", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "395": { zone: "warm", region: "Mississippi", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // Texas - Warm
  "750": { zone: "warm", region: "Dallas, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "751": { zone: "warm", region: "Dallas, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "752": { zone: "warm", region: "Dallas, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "753": { zone: "warm", region: "Dallas, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "760": { zone: "warm", region: "Fort Worth, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "770": { zone: "warm", region: "Houston, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "771": { zone: "warm", region: "Houston, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "772": { zone: "warm", region: "Houston, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "773": { zone: "warm", region: "Houston, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "774": { zone: "warm", region: "Houston, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "775": { zone: "warm", region: "Galveston, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "780": { zone: "warm", region: "San Antonio, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "781": { zone: "warm", region: "San Antonio, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "782": { zone: "warm", region: "San Antonio, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "783": { zone: "warm", region: "Corpus Christi, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "785": { zone: "warm", region: "McAllen, TX", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "786": { zone: "warm", region: "Austin, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "787": { zone: "warm", region: "Austin, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "789": { zone: "warm", region: "Austin, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "790": { zone: "warm", region: "Amarillo, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "791": { zone: "warm", region: "Amarillo, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "793": { zone: "warm", region: "Lubbock, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "797": { zone: "warm", region: "Midland, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "798": { zone: "warm", region: "El Paso, TX", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // Carolinas / Virginia - Transition
  "270": { zone: "transition", region: "Charlotte, NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "272": { zone: "transition", region: "Raleigh, NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "274": { zone: "transition", region: "Greensboro, NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "276": { zone: "transition", region: "Raleigh, NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "277": { zone: "transition", region: "Durham, NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "278": { zone: "transition", region: "Rocky Mount, NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "280": { zone: "warm", region: "Coastal NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "284": { zone: "warm", region: "Wilmington, NC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "290": { zone: "warm", region: "Columbia, SC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "292": { zone: "warm", region: "Columbia, SC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "293": { zone: "warm", region: "Charleston, SC", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "294": { zone: "warm", region: "Greenville, SC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "220": { zone: "transition", region: "Northern Virginia", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "221": { zone: "transition", region: "Northern Virginia", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "222": { zone: "transition", region: "Arlington, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "223": { zone: "transition", region: "Alexandria, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "230": { zone: "transition", region: "Richmond, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "231": { zone: "transition", region: "Richmond, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "232": { zone: "transition", region: "Richmond, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "234": { zone: "warm", region: "Virginia Beach, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "235": { zone: "warm", region: "Norfolk, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // Louisiana / Georgia coast - Warm
  "700": { zone: "warm", region: "New Orleans, LA", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "701": { zone: "warm", region: "New Orleans, LA", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "703": { zone: "warm", region: "New Orleans, LA", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "704": { zone: "warm", region: "Shreveport, LA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "706": { zone: "warm", region: "Shreveport, LA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "707": { zone: "warm", region: "Baton Rouge, LA", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "708": { zone: "warm", region: "Baton Rouge, LA", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "310": { zone: "warm", region: "Savannah, GA", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "314": { zone: "warm", region: "Savannah, GA", suggestedGrass: "St. Augustine", suggestedGrassKey: "st_augustine" },
  "316": { zone: "warm", region: "Valdosta, GA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "318": { zone: "warm", region: "Columbus, GA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "319": { zone: "warm", region: "Augusta, GA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // Northeast / Midwest — Cool season
  "010": { zone: "cool", region: "Massachusetts", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "011": { zone: "cool", region: "Massachusetts", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "012": { zone: "cool", region: "Massachusetts", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "013": { zone: "cool", region: "Springfield, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "014": { zone: "cool", region: "Worcester, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "015": { zone: "cool", region: "Worcester, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "016": { zone: "cool", region: "Worcester, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "017": { zone: "cool", region: "Framingham, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "018": { zone: "cool", region: "Woburn, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "019": { zone: "cool", region: "Lynn, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "020": { zone: "cool", region: "Boston, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "021": { zone: "cool", region: "Boston, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "022": { zone: "cool", region: "Boston, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "023": { zone: "cool", region: "Brockton, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "024": { zone: "cool", region: "Lexington, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "025": { zone: "cool", region: "Buzzards Bay, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "026": { zone: "cool", region: "Cape Cod, MA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "027": { zone: "cool", region: "Providence, RI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "028": { zone: "cool", region: "Providence, RI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "029": { zone: "cool", region: "Rhode Island", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "030": { zone: "cool", region: "New Hampshire", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "031": { zone: "cool", region: "Manchester, NH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "032": { zone: "cool", region: "New Hampshire", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "033": { zone: "cool", region: "Concord, NH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "034": { zone: "cool", region: "New Hampshire", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "035": { zone: "cool", region: "Vermont", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "036": { zone: "cool", region: "Vermont", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "037": { zone: "cool", region: "Vermont", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "038": { zone: "cool", region: "Vermont", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "039": { zone: "cool", region: "Maine", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "040": { zone: "cool", region: "Portland, ME", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "041": { zone: "cool", region: "Portland, ME", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "042": { zone: "cool", region: "Maine", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "043": { zone: "cool", region: "Maine", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "044": { zone: "cool", region: "Bangor, ME", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "045": { zone: "cool", region: "Bath, ME", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "046": { zone: "cool", region: "Maine", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "047": { zone: "cool", region: "Maine", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "048": { zone: "cool", region: "Maine", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "049": { zone: "cool", region: "Maine", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "050": { zone: "cool", region: "Vermont", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "054": { zone: "cool", region: "Burlington, VT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "060": { zone: "cool", region: "Hartford, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "061": { zone: "cool", region: "Hartford, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "062": { zone: "cool", region: "Hartford, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "063": { zone: "cool", region: "New London, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "064": { zone: "cool", region: "New London, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "065": { zone: "cool", region: "New Haven, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "066": { zone: "cool", region: "Bridgeport, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "067": { zone: "cool", region: "Waterbury, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "068": { zone: "cool", region: "Stamford, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "069": { zone: "cool", region: "Stamford, CT", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "070": { zone: "cool", region: "Newark, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "071": { zone: "cool", region: "Newark, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "072": { zone: "cool", region: "Elizabeth, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "073": { zone: "cool", region: "Jersey City, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "074": { zone: "cool", region: "Paterson, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "075": { zone: "cool", region: "Paterson, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "076": { zone: "cool", region: "Hackensack, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "077": { zone: "cool", region: "Red Bank, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "078": { zone: "cool", region: "New Brunswick, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "079": { zone: "cool", region: "Summit, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "080": { zone: "cool", region: "South NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "081": { zone: "cool", region: "Camden, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "082": { zone: "cool", region: "South NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "083": { zone: "cool", region: "Atlantic City, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "085": { zone: "cool", region: "Trenton, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "086": { zone: "cool", region: "Trenton, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "087": { zone: "cool", region: "South NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "088": { zone: "cool", region: "New Brunswick, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "089": { zone: "cool", region: "New Brunswick, NJ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "100": { zone: "cool", region: "New York, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "101": { zone: "cool", region: "New York, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "102": { zone: "cool", region: "New York, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "103": { zone: "cool", region: "Staten Island, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "104": { zone: "cool", region: "Bronx, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "105": { zone: "cool", region: "Westchester, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "106": { zone: "cool", region: "White Plains, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "107": { zone: "cool", region: "Yonkers, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "108": { zone: "cool", region: "New Rochelle, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "109": { zone: "cool", region: "Suffern, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "110": { zone: "cool", region: "Long Island, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "111": { zone: "cool", region: "Long Island City, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "112": { zone: "cool", region: "Brooklyn, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "113": { zone: "cool", region: "Flushing, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "114": { zone: "cool", region: "Jamaica, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "115": { zone: "cool", region: "Western Nassau, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "116": { zone: "cool", region: "Long Island, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "117": { zone: "cool", region: "Hicksville, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "118": { zone: "cool", region: "Hicksville, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "119": { zone: "cool", region: "Riverhead, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "120": { zone: "cool", region: "Albany, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "121": { zone: "cool", region: "Albany, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "122": { zone: "cool", region: "Albany, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "130": { zone: "cool", region: "Syracuse, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "131": { zone: "cool", region: "Syracuse, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "140": { zone: "cool", region: "Buffalo, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "141": { zone: "cool", region: "Buffalo, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "142": { zone: "cool", region: "Buffalo, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "143": { zone: "cool", region: "Niagara Falls, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "144": { zone: "cool", region: "Rochester, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "145": { zone: "cool", region: "Rochester, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "146": { zone: "cool", region: "Rochester, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "147": { zone: "cool", region: "Jamestown, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "148": { zone: "cool", region: "Elmira, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "149": { zone: "cool", region: "Binghamton, NY", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },

  // Pennsylvania
  "150": { zone: "cool", region: "Pittsburgh, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "151": { zone: "cool", region: "Pittsburgh, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "152": { zone: "cool", region: "Pittsburgh, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "153": { zone: "cool", region: "Pittsburgh, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "154": { zone: "cool", region: "Pittsburgh, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "155": { zone: "cool", region: "Johnstown, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "160": { zone: "cool", region: "New Castle, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "161": { zone: "cool", region: "New Castle, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "162": { zone: "cool", region: "New Castle, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "168": { zone: "cool", region: "Altoona, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "169": { zone: "cool", region: "Wellsboro, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "170": { zone: "cool", region: "Harrisburg, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "171": { zone: "cool", region: "Harrisburg, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "172": { zone: "cool", region: "Chambersburg, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "173": { zone: "cool", region: "York, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "174": { zone: "cool", region: "York, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "175": { zone: "cool", region: "Lancaster, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "176": { zone: "cool", region: "Lancaster, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "180": { zone: "cool", region: "Lehigh Valley, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "181": { zone: "cool", region: "Allentown, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "182": { zone: "cool", region: "Hazleton, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "183": { zone: "cool", region: "Stroudsburg, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "184": { zone: "cool", region: "Scranton, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "185": { zone: "cool", region: "Scranton, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "186": { zone: "cool", region: "Wilkes-Barre, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "187": { zone: "cool", region: "Wilkes-Barre, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "188": { zone: "cool", region: "Scranton, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "189": { zone: "cool", region: "Doylestown, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "190": { zone: "cool", region: "Philadelphia, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "191": { zone: "cool", region: "Philadelphia, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "192": { zone: "cool", region: "Philadelphia, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "193": { zone: "cool", region: "South Philly, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "194": { zone: "cool", region: "Norristown, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "195": { zone: "cool", region: "Reading, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "196": { zone: "cool", region: "Reading, PA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },

  // Maryland / DC
  "200": { zone: "transition", region: "Washington, DC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "201": { zone: "transition", region: "Dulles, VA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "202": { zone: "transition", region: "Washington, DC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "203": { zone: "transition", region: "Washington, DC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "204": { zone: "transition", region: "Washington, DC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "205": { zone: "transition", region: "Washington, DC", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "206": { zone: "transition", region: "Southern MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "207": { zone: "transition", region: "Southern MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "208": { zone: "transition", region: "Laurel, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "209": { zone: "transition", region: "Silver Spring, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "210": { zone: "transition", region: "Linthicum, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "211": { zone: "transition", region: "Baltimore, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "212": { zone: "transition", region: "Baltimore, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "214": { zone: "transition", region: "Annapolis, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "215": { zone: "transition", region: "Cumberland, MD", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "216": { zone: "transition", region: "Easton, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "217": { zone: "transition", region: "Frederick, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "218": { zone: "transition", region: "Salisbury, MD", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "219": { zone: "transition", region: "Elkton, MD", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },

  // Ohio / Midwest
  "430": { zone: "cool", region: "Columbus, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "431": { zone: "cool", region: "Columbus, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "432": { zone: "cool", region: "Columbus, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "440": { zone: "cool", region: "Cleveland, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "441": { zone: "cool", region: "Cleveland, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "442": { zone: "cool", region: "Akron, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "443": { zone: "cool", region: "Akron, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "444": { zone: "cool", region: "Youngstown, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "445": { zone: "cool", region: "Youngstown, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "446": { zone: "cool", region: "Canton, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "447": { zone: "cool", region: "Canton, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "448": { zone: "cool", region: "Mansfield, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "449": { zone: "cool", region: "Mansfield, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "450": { zone: "cool", region: "Cincinnati, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "451": { zone: "cool", region: "Cincinnati, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "452": { zone: "cool", region: "Cincinnati, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "453": { zone: "cool", region: "Dayton, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "454": { zone: "cool", region: "Dayton, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "455": { zone: "cool", region: "Springfield, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "456": { zone: "cool", region: "Chillicothe, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "457": { zone: "cool", region: "Athens, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "458": { zone: "cool", region: "Lima, OH", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },

  // Illinois / Indiana / Michigan / Wisconsin — Cool
  "460": { zone: "cool", region: "Indianapolis, IN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "461": { zone: "cool", region: "Indianapolis, IN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "462": { zone: "cool", region: "Indianapolis, IN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "480": { zone: "cool", region: "Detroit, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "481": { zone: "cool", region: "Detroit, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "482": { zone: "cool", region: "Detroit, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "483": { zone: "cool", region: "Royal Oak, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "484": { zone: "cool", region: "Flint, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "485": { zone: "cool", region: "Flint, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "486": { zone: "cool", region: "Saginaw, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "487": { zone: "cool", region: "Saginaw, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "488": { zone: "cool", region: "Lansing, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "489": { zone: "cool", region: "Lansing, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "490": { zone: "cool", region: "Kalamazoo, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "491": { zone: "cool", region: "Kalamazoo, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "492": { zone: "cool", region: "Jackson, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "493": { zone: "cool", region: "Grand Rapids, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "494": { zone: "cool", region: "Muskegon, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "495": { zone: "cool", region: "Grand Rapids, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "496": { zone: "cool", region: "Traverse City, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "497": { zone: "cool", region: "Gaylord, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "498": { zone: "cool", region: "Iron Mountain, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "499": { zone: "cool", region: "Iron Mountain, MI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "530": { zone: "cool", region: "Milwaukee, WI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "531": { zone: "cool", region: "Milwaukee, WI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "532": { zone: "cool", region: "Milwaukee, WI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "534": { zone: "cool", region: "Racine, WI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "535": { zone: "cool", region: "Madison, WI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "537": { zone: "cool", region: "Madison, WI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "540": { zone: "cool", region: "St. Paul, MN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "541": { zone: "cool", region: "Green Bay, WI", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "550": { zone: "cool", region: "Minneapolis, MN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "551": { zone: "cool", region: "St. Paul, MN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "553": { zone: "cool", region: "Minneapolis, MN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "554": { zone: "cool", region: "Minneapolis, MN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "555": { zone: "cool", region: "Minneapolis, MN", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "600": { zone: "cool", region: "Chicago, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "601": { zone: "cool", region: "Chicago, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "602": { zone: "cool", region: "Evanston, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "603": { zone: "cool", region: "Oak Park, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "604": { zone: "cool", region: "South Chicago, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "605": { zone: "cool", region: "Chicago suburbs, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "606": { zone: "cool", region: "Chicago, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "610": { zone: "cool", region: "Rockford, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "611": { zone: "cool", region: "Rockford, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "612": { zone: "cool", region: "Rock Island, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "613": { zone: "cool", region: "La Salle, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "614": { zone: "cool", region: "Galesburg, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "615": { zone: "cool", region: "Peoria, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "616": { zone: "cool", region: "Peoria, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "617": { zone: "cool", region: "Bloomington, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "618": { zone: "cool", region: "Champaign, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "619": { zone: "cool", region: "Champaign, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "620": { zone: "cool", region: "Springfield, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "622": { zone: "transition", region: "East St. Louis, IL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "623": { zone: "cool", region: "Quincy, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "624": { zone: "cool", region: "Effingham, IL", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "625": { zone: "transition", region: "Southern IL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "626": { zone: "transition", region: "Southern IL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "627": { zone: "transition", region: "Southern IL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "628": { zone: "transition", region: "Centralia, IL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "629": { zone: "transition", region: "Carbondale, IL", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // Missouri / Kansas — Transition/Cool
  "630": { zone: "transition", region: "St. Louis, MO", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "631": { zone: "transition", region: "St. Louis, MO", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "640": { zone: "transition", region: "Kansas City, MO", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "641": { zone: "transition", region: "Kansas City, MO", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "650": { zone: "transition", region: "Jefferson City, MO", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "651": { zone: "transition", region: "Jefferson City, MO", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "660": { zone: "transition", region: "Kansas City, KS", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "661": { zone: "transition", region: "Kansas City, KS", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "662": { zone: "transition", region: "Shawnee Mission, KS", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "664": { zone: "transition", region: "Topeka, KS", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "665": { zone: "transition", region: "Topeka, KS", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "666": { zone: "transition", region: "Topeka, KS", suggestedGrass: "Zoysia", suggestedGrassKey: "zoysia" },
  "670": { zone: "transition", region: "Wichita, KS", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "671": { zone: "transition", region: "Wichita, KS", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "672": { zone: "transition", region: "South KS", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // Oklahoma / Arkansas — Warm/Transition
  "730": { zone: "warm", region: "Oklahoma City, OK", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "731": { zone: "warm", region: "Oklahoma City, OK", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "740": { zone: "warm", region: "Tulsa, OK", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "741": { zone: "warm", region: "Tulsa, OK", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "720": { zone: "warm", region: "Little Rock, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "721": { zone: "warm", region: "Little Rock, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "722": { zone: "warm", region: "Little Rock, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "723": { zone: "warm", region: "West Memphis, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "724": { zone: "warm", region: "Jonesboro, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "725": { zone: "warm", region: "Batesville, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "726": { zone: "transition", region: "Harrison, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "727": { zone: "warm", region: "Fayetteville, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "728": { zone: "warm", region: "Russellville, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "729": { zone: "warm", region: "Fort Smith, AR", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // Arizona — Warm
  "850": { zone: "warm", region: "Phoenix, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "851": { zone: "warm", region: "Phoenix, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "852": { zone: "warm", region: "Mesa, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "853": { zone: "warm", region: "Chandler, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "855": { zone: "warm", region: "Globe, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "856": { zone: "warm", region: "Tucson, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "857": { zone: "warm", region: "Tucson, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "859": { zone: "cool", region: "Flagstaff, AZ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "860": { zone: "cool", region: "Flagstaff, AZ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "863": { zone: "cool", region: "Prescott, AZ", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "864": { zone: "warm", region: "Kingman, AZ", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "865": { zone: "warm", region: "Gallup, NM", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },

  // California
  "900": { zone: "warm", region: "Los Angeles, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "901": { zone: "warm", region: "Los Angeles, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "902": { zone: "warm", region: "Inglewood, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "903": { zone: "warm", region: "Inglewood, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "904": { zone: "warm", region: "Santa Monica, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "905": { zone: "warm", region: "Torrance, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "906": { zone: "warm", region: "Whittier, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "907": { zone: "warm", region: "Long Beach, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "908": { zone: "warm", region: "Long Beach, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "910": { zone: "warm", region: "Pasadena, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "911": { zone: "warm", region: "Pasadena, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "912": { zone: "warm", region: "Glendale, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "913": { zone: "warm", region: "Van Nuys, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "914": { zone: "warm", region: "Van Nuys, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "915": { zone: "warm", region: "Burbank, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "916": { zone: "warm", region: "North Hollywood, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "917": { zone: "warm", region: "Alhambra, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "918": { zone: "warm", region: "Alhambra, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "919": { zone: "warm", region: "San Diego, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "920": { zone: "warm", region: "San Diego, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "921": { zone: "warm", region: "San Diego, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "922": { zone: "warm", region: "Palm Desert, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "923": { zone: "warm", region: "San Bernardino, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "924": { zone: "warm", region: "San Bernardino, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "925": { zone: "warm", region: "Riverside, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "926": { zone: "warm", region: "Anaheim, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "927": { zone: "warm", region: "Santa Ana, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "928": { zone: "warm", region: "Anaheim, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "930": { zone: "warm", region: "Oxnard, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "931": { zone: "warm", region: "Santa Barbara, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "932": { zone: "warm", region: "Bakersfield, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "933": { zone: "warm", region: "Bakersfield, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "934": { zone: "cool", region: "Santa Cruz, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "935": { zone: "warm", region: "Fresno, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "936": { zone: "warm", region: "Fresno, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "937": { zone: "warm", region: "Fresno, CA", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "939": { zone: "cool", region: "Salinas, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "940": { zone: "cool", region: "San Francisco, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "941": { zone: "cool", region: "San Francisco, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "942": { zone: "cool", region: "Sacramento, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "943": { zone: "cool", region: "Palo Alto, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "944": { zone: "cool", region: "San Mateo, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "945": { zone: "cool", region: "Oakland, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "946": { zone: "cool", region: "Oakland, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "947": { zone: "cool", region: "Berkeley, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "948": { zone: "cool", region: "Richmond, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "949": { zone: "cool", region: "San Rafael, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "950": { zone: "cool", region: "San Jose, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "951": { zone: "cool", region: "San Jose, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "952": { zone: "cool", region: "Stockton, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "953": { zone: "cool", region: "Stockton, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "954": { zone: "cool", region: "Santa Rosa, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "955": { zone: "cool", region: "Eureka, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "956": { zone: "cool", region: "Sacramento, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "957": { zone: "cool", region: "Sacramento, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "958": { zone: "cool", region: "Sacramento, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "959": { zone: "cool", region: "Marysville, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "960": { zone: "cool", region: "Redding, CA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "961": { zone: "cool", region: "Reno, NV", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },

  // Colorado
  "800": { zone: "cool", region: "Denver, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "801": { zone: "cool", region: "Denver, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "802": { zone: "cool", region: "Denver, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "803": { zone: "cool", region: "Boulder, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "804": { zone: "cool", region: "Denver, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "805": { zone: "cool", region: "Longmont, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "806": { zone: "cool", region: "Colorado Springs, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "808": { zone: "cool", region: "Colorado Springs, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "809": { zone: "cool", region: "Pueblo, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "810": { zone: "cool", region: "Pueblo, CO", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },

  // Pacific NW — Cool
  "970": { zone: "cool", region: "Portland, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "971": { zone: "cool", region: "Portland, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "972": { zone: "cool", region: "Portland, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "973": { zone: "cool", region: "Salem, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "974": { zone: "cool", region: "Eugene, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "975": { zone: "cool", region: "Medford, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "976": { zone: "cool", region: "Klamath Falls, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "977": { zone: "cool", region: "Bend, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "978": { zone: "cool", region: "Pendleton, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "979": { zone: "cool", region: "Boise, ID", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "980": { zone: "cool", region: "Seattle, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "981": { zone: "cool", region: "Seattle, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "982": { zone: "cool", region: "Everett, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "983": { zone: "cool", region: "Tacoma, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "984": { zone: "cool", region: "Tacoma, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "985": { zone: "cool", region: "Olympia, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "986": { zone: "cool", region: "Portland, OR", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "988": { zone: "cool", region: "Wenatchee, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "989": { zone: "cool", region: "Yakima, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "990": { zone: "cool", region: "Spokane, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "991": { zone: "cool", region: "Spokane, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "992": { zone: "cool", region: "Spokane, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "993": { zone: "cool", region: "Pasco, WA", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "994": { zone: "cool", region: "Lewiston, ID", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "995": { zone: "cool", region: "Anchorage, AK", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "996": { zone: "cool", region: "Anchorage, AK", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "997": { zone: "cool", region: "Fairbanks, AK", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "998": { zone: "cool", region: "Juneau, AK", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "999": { zone: "cool", region: "Ketchikan, AK", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" },
  "967": { zone: "warm", region: "Hawaii", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
  "968": { zone: "warm", region: "Hawaii", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" },
};

// Fallback by zone based on first digit grouping
function getDefaultByFirstDigit(zip: string): RegionInfo {
  const first = zip.charAt(0);
  // 0-1: Northeast (cool), 2-3: Southeast (warm/transition), 4-5: Midwest (cool)
  // 6: Central (transition), 7: South-Central (warm), 8: Mountain (cool/warm), 9: West (cool/warm)
  switch (first) {
    case "0":
    case "1":
      return { zone: "cool", region: "Northeast", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" };
    case "2":
      return { zone: "transition", region: "Mid-Atlantic", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" };
    case "3":
      return { zone: "warm", region: "Southeast", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" };
    case "4":
    case "5":
      return { zone: "cool", region: "Midwest", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" };
    case "6":
      return { zone: "cool", region: "Central US", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" };
    case "7":
      return { zone: "warm", region: "South-Central", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" };
    case "8":
      return { zone: "cool", region: "Mountain West", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" };
    case "9":
      return { zone: "cool", region: "West Coast", suggestedGrass: "Fescue, Bluegrass, Rye", suggestedGrassKey: "cool_season" };
    default:
      return { zone: "warm", region: "your area", suggestedGrass: "Bermuda", suggestedGrassKey: "bermuda" };
  }
}

export function getRegionInfo(zip: string): RegionInfo {
  const prefix = zip.substring(0, 3);
  return zipPrefixMap[prefix] || getDefaultByFirstDigit(zip);
}

export type { RegionInfo, ClimateZone };
